/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package las.view;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import las.config.MyConnection;

/**
 *
 * @author Vinnu
 */
public class CurrentBatchView extends javax.swing.JDialog {

    /**
     * Creates new form CurrentBatchView
     */
    public CurrentBatchView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        titleSeperator = new javax.swing.JSeparator();
        currentBatchLabel = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        currentBatchTextField = new javax.swing.JTextField();
        fetchButton = new javax.swing.JButton();
        subjectTextField = new javax.swing.JTextField();
        descriptionScroll = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        warningLabel = new javax.swing.JLabel();
        changeButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Current Batch - Lab Assessment System v1.0b");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Lab Assessment System v1.0b");

        currentBatchLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currentBatchLabel.setText("Current Batch :");

        subjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subjectLabel.setText("Subject :");

        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        descriptionLabel.setText("Description :");

        currentBatchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                currentBatchTextFieldFocusLost(evt);
            }
        });

        fetchButton.setText("View");
        fetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchButtonActionPerformed(evt);
            }
        });

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionScroll.setViewportView(descriptionTextArea);

        warningLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(153, 0, 0));
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        changeButton.setText("Change Current Batch");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add New Batch");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleSeperator, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentBatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(currentBatchTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fetchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(descriptionScroll))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(subjectTextField)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentBatchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentBatchLabel))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fetchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Connection con = MyConnection.getConnection();
            PreparedStatement ps = con.prepareCall("select * from batch where current = ?");
            ps.setBoolean(1, true);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                currentBatchTextField.setText(rs.getString(1));
                subjectTextField.setText(rs.getString(2));
                descriptionTextArea.setText(rs.getString(3));
            } else {
                warningLabel.setForeground(Color.red);
                warningLabel.setText("No current batch available");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CurrentBatchView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CurrentBatchView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void fetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchButtonActionPerformed
        try {
            Connection con = MyConnection.getConnection();
            PreparedStatement ps = con.prepareCall("select * from batch where idbatch = ?");
            ps.setInt(1, Integer.parseInt(currentBatchTextField.getText()));
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                currentBatchTextField.setText(rs.getString(1));
                subjectTextField.setText(rs.getString(2));
                descriptionTextArea.setText(rs.getString(3));
            } else {
                warningLabel.setForeground(Color.red);
                warningLabel.setText("No current batch available");
            }
        } catch (Exception e) {
            warningLabel.setForeground(Color.red);
            warningLabel.setText("Invalid Batch Number.!");
        }
    }//GEN-LAST:event_fetchButtonActionPerformed

    private void currentBatchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currentBatchTextFieldFocusLost
        try {
            Connection con = MyConnection.getConnection();
            PreparedStatement ps = con.prepareCall("select * from batch where idbatch = ?");
            ps.setInt(1, Integer.parseInt(currentBatchTextField.getText()));
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                currentBatchTextField.setText(rs.getString(1));
                subjectTextField.setText(rs.getString(2));
                descriptionTextArea.setText(rs.getString(3));
                changeButton.setEnabled(true);
            } else {
                subjectTextField.setText("");
                warningLabel.setForeground(Color.red);
                descriptionTextArea.setText("");
                warningLabel.setText("No current batch available");
                changeButton.setEnabled(false);
            }
        } catch (Exception e) {
            warningLabel.setForeground(Color.red);
            warningLabel.setText("Invalid Batch Number.!");
        }
    }//GEN-LAST:event_currentBatchTextFieldFocusLost

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        try {
            Connection con = MyConnection.getConnection();
            PreparedStatement ps = con.prepareCall("update batch set current = ?");
            ps.setBoolean(1, false);
            ps.executeUpdate();
            ps = con.prepareCall("update batch set current = ? where idbatch = ?");
            ps.setBoolean(1, true);
            ps.setInt(2, Integer.parseInt(currentBatchTextField.getText()));
            ps.executeUpdate();
            warningLabel.setForeground(Color.green);
            warningLabel.setText("Current Batch Changed !");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CurrentBatchView.class.getName()).log(Level.SEVERE, null, ex);
            warningLabel.setText("Unable to Change the Current Batch...!");
            warningLabel.setForeground(Color.red);
        } catch (SQLException ex) {
            Logger.getLogger(CurrentBatchView.class.getName()).log(Level.SEVERE, null, ex);
            warningLabel.setText("Unable to Change the Current Batch...!");
            warningLabel.setForeground(Color.red);
        } catch (Exception ex) {
            Logger.getLogger(CurrentBatchView.class.getName()).log(Level.SEVERE, null, ex);
            warningLabel.setText("Invalid Batch Number ");
            warningLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (subjectTextField.getText().length() > 0) {
            try {
                Connection con = MyConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("insert into batch(subject, description, current) values(?,?,?)", PreparedStatement.RETURN_GENERATED_KEYS);
                ps.setString(1, subjectTextField.getText());
                ps.setString(2, descriptionTextArea.getText());
                ps.setBoolean(3, false);
                ps.executeUpdate();
                ResultSet rs = ps.getGeneratedKeys();
                if (rs.next()) {
                    warningLabel.setForeground(Color.green);
                    warningLabel.setText("Batch Added ! Batch ID : " + rs.getInt(1));
                    subjectTextField.setText("");
                    descriptionTextArea.setText("");
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CurrentBatchView.class.getName()).log(Level.SEVERE, null, ex);
                warningLabel.setText("Unable to add new batch... !");
                warningLabel.setForeground(Color.red);
            } catch (SQLException ex) {
                Logger.getLogger(CurrentBatchView.class.getName()).log(Level.SEVERE, null, ex);
                warningLabel.setText("Unable to add new batch... !");
                warningLabel.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentBatchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentBatchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentBatchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentBatchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CurrentBatchView dialog = new CurrentBatchView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel currentBatchLabel;
    private javax.swing.JTextField currentBatchTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JScrollPane descriptionScroll;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton fetchButton;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField subjectTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JSeparator titleSeperator;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
